import Queen from "./pages/developers/2e31c0";
import Murdock from "./pages/developers/3f7099";
import Lucas from "./pages/developers/8a6ca5";
import Grimm from "./pages/developers/27ff01";
import Richards from "./pages/developers/0459bb";
import Spencer from "./pages/developers/1270f5";
import Liang from "./pages/developers/62328c";
import Douglas from "./pages/developers/5adff2";
import Rogers from "./pages/developers/601892";
import Blaze from "./pages/developers/672957";
import Wilson from "./pages/developers/c29e3b";
import Savage from "./pages/developers/dcb916";
import Barton from "./pages/developers/8f112e";
import Banner from "./pages/developers/ae6248";
import Secord from "./pages/developers/0c04a5";
import Javert from "./pages/developers/7b81ce";
import Barnes from "./pages/developers/5f84d3";
import Parker from "./pages/developers/9f15b7";
import Allen from "./pages/developers/65f1f4";
import Jordan from "./pages/developers/4ba90e";
import Wayne from "./pages/developers/49f40f";
import Mason from "./pages/developers/405d4a";
import Drake from "./pages/developers/ae37ba";
import Kord from "./pages/developers/af5bf7";
import Nelson from "./pages/developers/df2916";
import Free from "./pages/developers/de412a";
import Smith from "./pages/developers/34b12a";

export const Quee = Queen;
export const Murd = Murdock;
export const Luca = Lucas;
export const Grim = Grimm;
export const Rich = Richards;
export const Spen = Spencer;
export const Lian = Liang;
export const Doug = Douglas;
export const Roge = Rogers;
export const Blaz = Blaze;
export const Wils = Wilson;
export const Sava = Savage;
export const Bart = Barton;
export const Bann = Banner;
export const Seco = Secord;
export const Jave = Javert;
export const Barn = Barnes;
export const Park = Parker;
export const Alle = Allen;
export const Jord = Jordan;
export const Wayn = Wayne;
export const Maso = Mason;
export const Drak = Drake;
export const Kor = Kord;
export const Nels = Nelson;
export const Fre = Free;
export const Smit = Smith;
